<a href="https://colab.research.google.com/github/Raaj-4320/Accident-analysis/blob/EDA/Accident-analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Columns

* INDEX_ : Unique Identifier
* ACCNUM : Accident Number
* YEAR : Year Collision Occurred
* DATE : Date Collision Occurred (time is displayed in UTC format)
* TIME : Time Collision Occurred
* STREET1 : Street Collision Occurred
* STREET2 : Street Collision Occurred
* OFFSET : Distance and direction of the Collision
* ROAD_CLASS : Road Classification
* DISTRICT : City District
* WARDNUM : City of Toronto Ward collision occurred
* LATITUDE : Latitude
* LONGITUDE : Longitude
* LOCCOORD : Location Coordinate
* ACCLOC : Collision Location
* TRAFFCTL : Traffic Control Type
* VISIBILITY : Environment Condition
* LIGHT : Light Condition
* RDSFCOND : Road Surface Condition
* ACCLASS : Classification of Accident
* IMPACTYPE : Initial Impact Type
* INVTYPE : Involvement Type
* INVAGE : Age of Involved Party
* INJURY : Severity of Injury
* FATAL_NO : Sequential Number
* INITDIR : Initial Direction of Travel
* VEHTYPE : Type of Vehicle
* MANOEUVER : Vehicle Manoeuver
* DRIVACT : Apparent Driver Action
* DRIVCOND : Driver Condition
* PEDTYPE : Pedestrian Crash Type - detail
* PEDACT : Pedestrian Action
* PEDCOND : Condition of Pedestrian
* CYCLISTYPE : Cyclist Crash Type - detail
* CYCACT : Cyclist Action
* CYCCOND : Cyclist Condition
* PEDESTRIAN : Pedestrian Involved In Collision
* CYCLIST : Cyclists Involved in Collision
* AUTOMOBILE : Driver Involved in Collision
* MOTORCYCLE : Motorcyclist Involved in Collision
* TRUCK : Truck Driver Involved in Collision
* TRSN_CITY_VEH : Transit or City Vehicle Involved in Collision
* EMERG_VEH : Emergency Vehicle Involved in Collision
* PASSENGER : Passenger Involved in Collision
* SPEEDING : Speeding Related Collision
* AG_DRIV : Aggressive and Distracted Driving Collision
* REDLIGHT : Red Light Related Collision
* ALCOHOL : Alcohol Related Collision
* DISABILITY : Medical or Physical Disability Related Collision
* HOOD_158 Unique ID : for City of Toronto Neighbourhood (new)
* NEIGHBOURHOOD_158 : City of Toronto Neighbourhood name (new)
* HOOD_140 : Unique ID for City of Toronto Neighbourhood (old)
* NEIGHBOURHOOD_140 : City of Toronto Neighbourhood name (old)
* DIVISION : Toronto Police Service Division
* ObjectID : Unique Identifier (auto generated)

In [170]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns
plt.style.use('ggplot')
pd.set_option('display.max_columns', None)

In [171]:
df = pd.read_csv("/content/drive/MyDrive/Datasets/Train.csv")


## Data Understanding

*   Dataframe shape
*   `head` and `tail`
*   dtypes
* describe


In [172]:
df.shape

(15000, 55)

In [173]:
df.head()

INDEX_    ACCNUM  YEAR                    DATE  TIME          STREET1  \
0  3387730  892658.0  2006  2006/03/11 05:00:00+00   852       BLOOR ST W   
1  3387731  892658.0  2006  2006/03/11 05:00:00+00   852       BLOOR ST W   
2  3388101  892810.0  2006  2006/03/11 05:00:00+00   915  MORNINGSIDE AVE   
3  3389067  893184.0  2006  2006/01/01 05:00:00+00   236     WOODBINE AVE   
4  3388102  892810.0  2006  2006/03/11 05:00:00+00   915  MORNINGSIDE AVE   

          STREET2 OFFSET      ROAD_CLASS               DISTRICT  WARDNUM  \
0     DUNDAS ST W    NaN  Major Arterial  Toronto and East York        4   
1     DUNDAS ST W    NaN  Major Arterial  Toronto and East York        4   
2  SHEPPARD AVE E    NaN  Major Arterial            Scarborough       25   
3     O CONNOR DR    NaN  Major Arterial  Toronto and East York       19   
4  SHEPPARD AVE E    NaN  Major Arterial            Scarborough       25   

    LATITUDE  LONGITUDE      LOCCOORD                ACCLOC        TRAFFCTL  \
0  43.656345 -79.452490  Intersection       At Intersection  Traffic Signal   
1  43.656345 -79.452490  Intersection       At Intersection  Traffic Signal   
2  43.801943 -79.199786  Intersection       At Intersection  Traffic Signal   
3  43.699595 -79.318797  Intersection  Intersection Related      No Control   
4  43.801943 -79.199786  Intersection       At Intersection  Traffic Signal   

  VISIBILITY     LIGHT RDSFCOND           ACCLASS              IMPACTYPE  \
0      Clear  Daylight      Dry             Fatal  Pedestrian Collisions   
1      Clear  Daylight      Dry             Fatal  Pedestrian Collisions   
2      Clear  Daylight      Dry             Fatal       Turning Movement   
3      Clear      Dark      Wet  Non-Fatal Injury            Approaching   
4      Clear  Daylight      Dry             Fatal       Turning Movement   

             INVTYPE    INVAGE INJURY  FATAL_NO INITDIR  \
0             Driver   unknown   None       NaN   South   
1         Pedestrian  65 to 69  Fatal       NaN   North   
2  Motorcycle Driver  45 to 49  Fatal       NaN    East   
3          Passenger  50 to 54  Major       NaN     NaN   
4             Driver   unknown   None       NaN   South   

                     VEHTYPE      MANOEUVER                       DRIVACT  \
0  Automobile, Station Wagon   Turning Left  Failed to Yield Right of Way   
1                      Other            NaN                           NaN   
2                 Motorcycle  Turning Right     Disobeyed Traffic Control   
3                        NaN            NaN                           NaN   
4  Automobile, Station Wagon    Going Ahead              Driving Properly   

  DRIVCOND                                            PEDTYPE  \
0  Unknown                                                NaN   
1      NaN  Vehicle turns left while ped crosses with ROW ...   
2  Unknown                                                NaN   
3      NaN                                                NaN   
4  Unknown                                                NaN   

                       PEDACT  PEDCOND CYCLISTYPE CYCACT CYCCOND PEDESTRIAN  \
0                         NaN      NaN        NaN    NaN     NaN        Yes   
1  Crossing with right of way  Unknown        NaN    NaN     NaN        Yes   
2                         NaN      NaN        NaN    NaN     NaN        NaN   
3                         NaN      NaN        NaN    NaN     NaN        NaN   
4                         NaN      NaN        NaN    NaN     NaN        NaN   

  CYCLIST AUTOMOBILE MOTORCYCLE TRUCK TRSN_CITY_VEH EMERG_VEH PASSENGER  \
0     NaN        Yes        NaN   NaN           NaN       NaN       NaN   
1     NaN        Yes        NaN   NaN           NaN       NaN       NaN   
2     NaN        Yes        Yes   NaN           NaN       NaN       NaN   
3     NaN        Yes        NaN   NaN           NaN       NaN       Yes   
4     NaN        Yes        Yes   NaN           NaN       NaN       NaN   

  SPEEDING AG_DRI

In [174]:
df.columns

Index(['INDEX_', 'ACCNUM', 'YEAR', 'DATE', 'TIME', 'STREET1', 'STREET2',
       'OFFSET', 'ROAD_CLASS', 'DISTRICT', 'WARDNUM', 'LATITUDE', 'LONGITUDE',
       'LOCCOORD', 'ACCLOC', 'TRAFFCTL', 'VISIBILITY', 'LIGHT', 'RDSFCOND',
       'ACCLASS', 'IMPACTYPE', 'INVTYPE', 'INVAGE', 'INJURY', 'FATAL_NO',
       'INITDIR', 'VEHTYPE', 'MANOEUVER', 'DRIVACT', 'DRIVCOND', 'PEDTYPE',
       'PEDACT', 'PEDCOND', 'CYCLISTYPE', 'CYCACT', 'CYCCOND', 'PEDESTRIAN',
       'CYCLIST', 'AUTOMOBILE', 'MOTORCYCLE', 'TRUCK', 'TRSN_CITY_VEH',
       'EMERG_VEH', 'PASSENGER', 'SPEEDING', 'AG_DRIV', 'REDLIGHT', 'ALCOHOL',
       'DISABILITY', 'HOOD_158', 'NEIGHBOURHOOD_158', 'HOOD_140',
       'NEIGHBOURHOOD_140', 'DIVISION', 'ObjectId'],
      dtype='object')

In [175]:
df.dtypes

INDEX_                 int64
ACCNUM               float64
YEAR                   int64
DATE                  object
TIME                   int64
STREET1               object
STREET2               object
OFFSET                object
ROAD_CLASS            object
DISTRICT              object
WARDNUM                int64
LATITUDE             float64
LONGITUDE            float64
LOCCOORD              object
ACCLOC                object
TRAFFCTL              object
VISIBILITY            object
LIGHT                 object
RDSFCOND              object
ACCLASS               object
IMPACTYPE             object
INVTYPE               object
INVAGE                object
INJURY                object
FATAL_NO             float64
INITDIR               object
VEHTYPE               object
MANOEUVER             object
DRIVACT               object
DRIVCOND              object
PEDTYPE               object
PEDACT                object
PEDCOND               object
CYCLISTYPE            object
CYCACT        

In [176]:
df.describe()

INDEX_        ACCNUM          YEAR          TIME       WARDNUM  \
count  1.500000e+04  1.130200e+04  15000.000000  15000.000000  1.500000e+04   
mean   2.897643e+07  3.193720e+08   2011.397200   1347.332800  2.862441e+03   
std    3.465401e+07  1.067084e+09      3.685531    631.600998  1.982925e+05   
min    3.363207e+06  1.284070e+05   2006.000000      0.000000  1.000000e+00   
25%    5.293513e+06  1.005723e+06   2008.000000    908.000000  7.000000e+00   
50%    6.714110e+06  1.158316e+06   2011.000000   1438.000000  1.300000e+01   
75%    8.024356e+07  1.308396e+06   2014.000000   1840.000000  2.200000e+01   
max    8.154201e+07  4.008024e+09   2018.000000   2359.000000  1.716222e+07   

           LATITUDE     LONGITUDE    FATAL_NO      ObjectId  
count  15000.000000  15000.000000  593.000000  15000.000000  
mean      43.710768    -79.396827   28.777403   7500.500000  
std        0.056158      0.104224   17.749125   4330.271354  
min       43.592047    -79.638390    1.000000      1.000000  
25%       43.662649    -79.470042   14.000000   3750.750000  
50%       43.702807    -79.397632   28.000000   7500.500000  
75%       43.756457    -79.319190   42.000000  11250.250000  
max       43.855445    -79.125896   78.000000  15000.000000

## Data preperation

* Dropping irrelavant columns and rows
* Identifying duplicated columns
* Remaming Columns
* Feature Creation

In [177]:
df[[
    'INDEX_',
    'ACCNUM', 'YEAR', 'DATE', 'TIME', 'STREET1', 'STREET2',
     #'OFFSET',
    'ROAD_CLASS', 'DISTRICT',
    'WARDNUM', 'LATITUDE', 'LONGITUDE',
    'LOCCOORD', 'ACCLOC', 'TRAFFCTL', 'VISIBILITY', 'LIGHT', 'RDSFCOND',
    'ACCLASS', 'IMPACTYPE', 'INVTYPE', 'INVAGE', 'INJURY', 'FATAL_NO',
    'INITDIR', 'VEHTYPE', 'MANOEUVER', 'DRIVACT', 'DRIVCOND',
     #'PEDTYPE',
     #'PEDACT',
     #'PEDCOND',
     #'CYCLISTYPE',
     #'CYCACT',
    'CYCCOND', 'PEDESTRIAN',
       'CYCLIST', 'AUTOMOBILE', 'MOTORCYCLE', 'TRUCK', 'TRSN_CITY_VEH',
       'EMERG_VEH', 'PASSENGER', 'SPEEDING', 'AG_DRIV', 'REDLIGHT', 'ALCOHOL',
       'DISABILITY', 'HOOD_158', 'NEIGHBOURHOOD_158', 'HOOD_140',
       'NEIGHBOURHOOD_140', 'DIVISION', 'ObjectId']].head()

INDEX_    ACCNUM  YEAR                    DATE  TIME          STREET1  \
0  3387730  892658.0  2006  2006/03/11 05:00:00+00   852       BLOOR ST W   
1  3387731  892658.0  2006  2006/03/11 05:00:00+00   852       BLOOR ST W   
2  3388101  892810.0  2006  2006/03/11 05:00:00+00   915  MORNINGSIDE AVE   
3  3389067  893184.0  2006  2006/01/01 05:00:00+00   236     WOODBINE AVE   
4  3388102  892810.0  2006  2006/03/11 05:00:00+00   915  MORNINGSIDE AVE   

          STREET2      ROAD_CLASS               DISTRICT  WARDNUM   LATITUDE  \
0     DUNDAS ST W  Major Arterial  Toronto and East York        4  43.656345   
1     DUNDAS ST W  Major Arterial  Toronto and East York        4  43.656345   
2  SHEPPARD AVE E  Major Arterial            Scarborough       25  43.801943   
3     O CONNOR DR  Major Arterial  Toronto and East York       19  43.699595   
4  SHEPPARD AVE E  Major Arterial            Scarborough       25  43.801943   

   LONGITUDE      LOCCOORD                ACCLOC        TRAFFCTL VISIBILITY  \
0 -79.452490  Intersection       At Intersection  Traffic Signal      Clear   
1 -79.452490  Intersection       At Intersection  Traffic Signal      Clear   
2 -79.199786  Intersection       At Intersection  Traffic Signal      Clear   
3 -79.318797  Intersection  Intersection Related      No Control      Clear   
4 -79.199786  Intersection       At Intersection  Traffic Signal      Clear   

      LIGHT RDSFCOND           ACCLASS              IMPACTYPE  \
0  Daylight      Dry             Fatal  Pedestrian Collisions   
1  Daylight      Dry             Fatal  Pedestrian Collisions   
2  Daylight      Dry             Fatal       Turning Movement   
3      Dark      Wet  Non-Fatal Injury            Approaching   
4  Daylight      Dry             Fatal       Turning Movement   

             INVTYPE    INVAGE INJURY  FATAL_NO INITDIR  \
0             Driver   unknown   None       NaN   South   
1         Pedestrian  65 to 69  Fatal       NaN   North   
2  Motorcycle Driver  45 to 49  Fatal       NaN    East   
3          Passenger  50 to 54  Major       NaN     NaN   
4             Driver   unknown   None       NaN   South   

                     VEHTYPE      MANOEUVER                       DRIVACT  \
0  Automobile, Station Wagon   Turning Left  Failed to Yield Right of Way   
1                      Other            NaN                           NaN   
2                 Motorcycle  Turning Right     Disobeyed Traffic Control   
3                        NaN            NaN                           NaN   
4  Automobile, Station Wagon    Going Ahead              Driving Properly   

  DRIVCOND CYCCOND PEDESTRIAN CYCLIST AUTOMOBILE MOTORCYCLE TRUCK  \
0  Unknown     NaN        Yes     NaN        Yes        NaN   NaN   
1      NaN     NaN        Yes     NaN        Yes        NaN   NaN   
2  Unknown     NaN        NaN     NaN        Yes        Yes   NaN   
3      NaN     NaN        NaN     NaN        Yes        NaN   NaN   
4  Unknown     NaN        NaN     NaN        Yes        Yes   NaN   

  TRSN_CITY_VEH EMERG_VEH PASSENGER SPEEDING AG_DRIV REDLIGHT ALCOHOL  \
0           NaN       NaN       NaN      NaN     Yes      NaN     NaN   
1           NaN       NaN       NaN      NaN     Yes      NaN     NaN   
2           NaN       NaN       NaN      NaN     Yes      Yes     NaN   
3           NaN       NaN       Yes      Yes     Yes      NaN     Yes   
4           NaN       NaN       NaN      NaN     Yes      Yes     NaN   

  DISABILITY HOOD_158 NEIGHBOURHOOD_158 HOOD_140      NEIGHBOURHOOD_140  \
0        NaN       88   High Park North       88   High Park North (88)   
1        NaN       88   High Park North       88   High Park North (88)   
2        NaN      146      Malvern East      132          Malvern (132)   
3        NaN       60  Woodbine-Lumsden       60  Woodbine-Lumsden (60)   
4        NaN      146      Malvern East      132          Malvern (132)   

  DIVISION  ObjectId  
0      D11         1  
1      D11         2  
2 

In [178]:
one_accident = df[df.duplicated(subset=[
    'YEAR',
    'DATE',
    'TIME',
    'STREET1',
    'WARDNUM',
    'LONGITUDE',
    'LATITUDE',
    'LIGHT',
    'HOOD_158',
    'NEIGHBOURHOOD_158',
    'HOOD_140',
    'NEIGHBOURHOOD_140',
    'DIVISION'
], keep=False)]

# Group by the condition and assign a unique index ID
one_accident['ACC_NUM'] = one_accident.groupby([
    'YEAR',
    'DATE',
    'TIME',
    'STREET1',
    'WARDNUM',
    'LONGITUDE',
    'LATITUDE',
    'LIGHT',
    'HOOD_158',
    'NEIGHBOURHOOD_158',
    'HOOD_140',
    'NEIGHBOURHOOD_140',
    'DIVISION'
]).ngroup()

# Merge the unique index IDs back to the original DataFrame
df = pd.merge(df, one_accident[['ACC_NUM']], left_index=True, right_index=True, how='left')

<ipython-input-178-83a82bd6d91f>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  one_accident['ACC_NUM'] = one_accident.groupby([


In [203]:
# First result: Total null values for each feature
null_counts = df.isnull().sum()
null_df = pd.DataFrame(null_counts, columns=["Missing Values"])

# Second result: Total unique values for each feature
unique_values = df.nunique().reset_index()
unique_values.columns = ["Feature", "Unique Values"]

# Combine the two DataFrames
combined_df = pd.merge(unique_values, null_df, left_on="Feature", right_index=True)

# Display the combined DataFrame
print(combined_df)

              Feature  Unique Values  Missing Values
0              INDEX_          15000               0
1              ACCNUM           3822            3698
2                YEAR             13               0
3                DATE           3082               0
4                TIME           1276               0
5             STREET1           1547               0
6             STREET2           2344            1343
7              OFFSET            339           13072
8          ROAD_CLASS              9             357
9            DISTRICT              4              14
10            WARDNUM             71               0
11           LATITUDE           3475               0
12          LONGITUDE           3901               0
13           LOCCOORD              7              90
14             ACCLOC              9            5450
15           TRAFFCTL             10              29
16         VISIBILITY              8              14
17              LIGHT              9          

In [202]:
# Find null values in the 'ACC_NUM' column
null_values_indices = df[df['ACC_NUM'].isnull()].index

# Generate a sequence starting from 4545
sequence = range(5005, 5005 + len(null_values_indices))

# Fill null values with the generated sequence
df.loc[null_values_indices, 'ACC_NUM'] = sequence

# Display the DataFrame with filled null values
df["ACC_NUM"].isna().sum()

0

In [181]:
# # Find null values
# null_indices = df.index[df['ACC_NUM'].isnull()]

# # Fill null values starting from 252
# fill_value = 252
# for null_index in null_indices:
#     df.at[null_index, 'ACC_NUM'] = fill_value
#     fill_value += 1

In [182]:
df["ACC_NUM"].unique()

array([  60.,   61.,    0., ..., 4820., 4783., 5003.])

In [209]:
df.duplicated(subset=[""]).sum()

0

In [184]:
df["PEDACT"].unique()

array([nan, 'Crossing with right of way', 'Crossing, no Traffic Control',
       'Running onto Roadway', 'Crossing without right of way',
       'On Sidewalk or Shoulder', 'Other',
       'Crossing, Pedestrian Crossover',
       'Coming From Behind Parked Vehicle', 'Pushing/Working on Vehicle',
       'Walking on Roadway Against Traffic',
       'Walking on Roadway with Traffic', 'Playing or Working on Highway',
       'Person Getting on/off Vehicle',
       'Crossing marked crosswalk without ROW',
       'Person Getting on/off School Bus'], dtype=object)

In [185]:
df["PEDCOND"].unique()


array([nan, 'Unknown', 'Normal', 'Other', 'Inattentive',
       'Had Been Drinking', 'Medical or Physical Disability',
       'Ability Impaired, Alcohol', 'Ability Impaired, Alcohol Over .80',
       'Ability Impaired, Drugs', 'Fatigue'], dtype=object)

In [186]:
df["CYCLISTYPE"].unique()


array([nan, 'Cyclist turns right across motorists path',
       'Motorist turned left across cyclists path.',
       'Cyclist without ROW rides into path of motorist at inter, lnwy, dwy-Cyclist not turn.',
       'Motorist without ROW drives into path of cyclist at inter, lnwy, dwy-Driver not turn.',
       'Motorist turns right at non-signal Inter.(stop, yield, no cont.,and dwy) and strikes cyclist.',
       'Motorist turning right on green or amber at signalized intersection strikes cyclist.',
       'Cyclist struck opened vehicle door',
       'Cyclist and Driver travelling in same direction. One vehicle sideswipes the other.',
       'Cyclist turned left across motorists path.',
       'Cyclist strikes pedestrian.',
       'Cyclist loses control and strikes object (pole, ttc track)',
       'Cyclist and Driver travelling in same direction. One vehicle rear-ended the other.',
       'Motorist turning right on red at signalized intersection strikes cyclist.',
       'Cyclist makes u-

In [187]:
df["CYCACT"].unique()


array([nan, 'Failed to Yield Right of Way', 'Driving Properly', 'Other',
       'Improper Passing', 'Disobeyed Traffic Control', 'Lost control',
       'Improper Turn', 'Improper Lane Change', 'Following too Close',
       'Speed too Fast For Condition', 'Wrong Way on One Way Road'],
      dtype=object)

In [188]:
df["PEDESTRIAN"] = df["PEDESTRIAN"].fillna("No")

In [189]:
df["CYCLIST"] = df["CYCLIST"].fillna("No")


In [190]:
df["AUTOMOBILE"] = df["AUTOMOBILE"].fillna("No")

In [191]:
df["MOTORCYCLE"] = df["MOTORCYCLE"].fillna("No")


In [192]:
df["TRUCK"] = df["TRUCK"].fillna("No")


In [193]:
df["TRSN_CITY_VEH"] = df["TRSN_CITY_VEH"].fillna("No")


In [194]:
df["EMERG_VEH"] = df["EMERG_VEH"].fillna("No")


In [195]:
df["PASSENGER"] = df["PASSENGER"].fillna("No")


In [196]:
df["SPEEDING"] = df["SPEEDING"].fillna("No")


In [197]:
df["AG_DRIV"] = df["AG_DRIV"].fillna("No")


In [198]:
df["ALCOHOL"] = df["ALCOHOL"].fillna("No")


In [199]:
df["DISABILITY"] = df["DISABILITY"].fillna("No")


In [200]:
df["REDLIGHT"] = df["REDLIGHT"].fillna("No")
